as yet unclassified
visitBPMN20InclusiveGatewayImpl: aModel
	"
	For an AND-split, the complexity is simply 1.
	CFCAND-split(a)= 1
	The designer constructing a process needs only to consider and analyze one state that may arise from the execution of an 	AND-split construct, since it is assumed that all the outgo- ing transitions are selected and followed. This rationale is 	illustrated in Figure 10.
	"
	^ 1